
- name: Run docker kibana container
  become: true
  docker:
    docker_api_version: "{{ docker_api_version }}"
    env: "{{ docker_kibana_env }}"
    expose: "{{ docker_kibana_expose }}"
    image: "{{ docker_kibana_image }}"
    name: "{{ docker_kibana_name }}"
    ports: "{{ docker_kibana_ports }}"
    links: "{{ docker_kibana_links }}"
    volumes: "{{ docker_kibana_volumes }}"
    command: "{{ docker_kibana_command }}"
    memory_limit: "{{ docker_kibana_memory_limit }}"
    log_driver: "{{ docker_kibana_log_driver }}"
    log_opt: "{{ docker_kibana_log_opt }}"
    pull: always
    restart_policy: always
    state: reloaded
  tags:
    - install
    - upgrade
